"""Symlink already-generated image folders into the open-set subfolder. CPU-only, reversible
(only creates links inside the NEW ``train_openset`` dir; never touches the source dirs).

``generate_images.py`` auto-skips caption folders that already contain n-images, so linking
the train/ (baseline) and train_demo/ folders of the reused captions means the GPU job renders
only the genuinely new captions, while the uncapped VQA still covers everything.

    python intersectional/link_reused_images.py            # uses the selection report
    python intersectional/link_reused_images.py --dry_run
"""
import os
import json
import argparse

REPORT = "results/intersectional/openset_selection_report.json"
SOURCES = ["sd_generated_dataset/coco/train_demo/sd-xl", "sd_generated_dataset/coco/train/sd-xl"]
DEST = "sd_generated_dataset/coco/train_openset/sd-xl"


def main(report_path, dry_run):
    with open(report_path) as f:
        reused = json.load(f)["reused_caption_ids"]
    os.makedirs(DEST, exist_ok=True)
    linked, missing, present = 0, [], 0
    for cid in reused:
        dst = os.path.join(DEST, cid)
        if os.path.exists(dst):
            present += 1
            continue
        src = next((os.path.join(s, cid) for s in SOURCES
                    if os.path.isdir(os.path.join(s, cid))), None)
        if src is None:
            missing.append(cid)
            continue
        if not dry_run:
            # relative link so the dataset root can move as a whole
            os.symlink(os.path.relpath(src, DEST), dst)
        linked += 1
    print(f"reused captions: {len(reused)} | linked: {linked} | already present: {present} "
          f"| missing source: {len(missing)}{' (DRY RUN)' if dry_run else ''}")
    if missing:
        print("missing (will be re-generated by the GPU job):", missing[:10],
              "..." if len(missing) > 10 else "")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--report", default=REPORT)
    p.add_argument("--dry_run", action="store_true")
    o = p.parse_args()
    main(o.report, o.dry_run)
